### ISSUE TITLE
Pygame didn't install in codespace

### ISSUE THREAD

**Issue by shanmithk** [league-curriculum/Python-Games#1]
I had to `pip install -r requirements.txt` to get started.

**Comment by NicholasWalton** [comment]
VS Code prompts the user to create a venv but `requirements.txt` is unchecked by default for the venv. Can we disable the venv prompt for this repo?

**Comment by ericbusboom** [comment]
Ah, so @shanmithk created the venv, based on the prompt, but did not select requirements.txt?

Not sure if we can disable it, but I've often wanted to do that, since it is unnecessary.
